name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY}}
          source: "."
          target: "/home/ubuntu/CPEN321-tutorial"
      - name: Rebuild & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY}}
          script: |
            cd /home/ubuntu/CPEN321-tutorial
            sudo rm -rf node_modules
            npm install
            cat > .env <<EOF
            PORT=${{ secrets.PROD_PORT }}
            DB_URI=${{ secrets.PROD_DB_URI }}
            EOF
            chmod 600 .env

            docker-compose down
            docker-compose --env-file .env build
            docker-compose --env-file .env up -d